spring:
    sleuth:
     sampler:
      probability: 1.0
    zipkin:
     base-url: http://192.168.0.188:9411/
    cloud:
         gateway:
            discovery:
              locator:
                enabled: true
                lower-case-service-id: true
            globalcors:
                corsConfigurations:
                  '[/**]':
                    allowedOrigins: "*"
                    allowed-methods:
                    - "*"
                    allowed-headers:
                    - "*"
                    allow-credentials: true

            routes:
            - id: clickerclass-user
              uri: lb://user-service
              predicates:
              - Path=/user/**
            - id: clickerclass-oauth
              uri: lb://oauth-service
              predicates:
              - Path=/oauth/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.188:8761/eureka
  instance:
    prefer-ip-address: true
oauth:
  enabled: true
  jwt:
    issuer: angular
    password: droptable2020..
    exclude-matchers:
    - method: POST
      paths:
      - \/user.*
    - method: GET
      paths:
      - \/user
    - method: PUT
      paths:
      - \/user
    - method: DELETE
      paths:
      - \/user
    matchers-with-role:
    - method: GET
      paths:
      - \/producto.*
      roles:
        - ROLE_ADMIN
    - method: POST
      paths:
      - \/producto.*
      roles:
        - ROLE_ADMIN
